apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    svc: consumer-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer-service
  labels:
    application: nFood-delivery
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: consumer-service
        application: nFood-delivery
    spec:
      containers:
        - name: consumer-service
          image: msapatterns/consumer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: httpport
---